# Generated by Django 4.1.6 on 2023-02-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appvoucher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
