# Generated by Django 4.1.6 on 2023-02-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appvoucher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
    ]
