# Generated by Django 4.1.6 on 2023-02-13 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appvoucher', '0002_company_remove_voucher_employee_delete_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giving_company_name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appvoucher.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('emp_company', models.CharField(max_length=20)),
                ('voucher_employee_have', models.IntegerField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appvoucher.company')),
                ('employee', models.ManyToManyField(related_name='employee', to='appvoucher.voucher')),
            ],
        ),
    ]
