# Generated by Django 4.1.6 on 2023-02-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appvoucher', '0002_alter_employee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=25, verbose_name='Employee'),
        ),
    ]
