# Generated by Django 4.1.6 on 2023-02-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appvoucher', '0003_voucher_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='giving_company_name',
        ),
    ]
