# Generated by Django 4.1.6 on 2023-02-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appvoucher', '0003_alter_employee_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=25),
        ),
    ]
