# Generated by Django 4.1.6 on 2023-02-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appvoucher', '0004_remove_voucher_giving_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=40),
        ),
    ]
