# Generated by Django 4.1.6 on 2023-02-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appvoucher', '0006_rename_employee_employee_voucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_company',
        ),
    ]
