# Generated by Django 4.1.6 on 2023-02-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appvoucher', '0007_remove_employee_emp_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='voucher_employee_have',
        ),
        migrations.AlterField(
            model_name='employee',
            name='voucher',
            field=models.ManyToManyField(related_name='employee_detail', to='appvoucher.voucher'),
        ),
    ]
